package com.example.starter.config;

public class SQLConst {

//  String sql = "CREATE TABLE TESTCONNECTDB (ID int generated by default as identity (start with 1 increment by 1) not null, NAME varchar(255), EMAIL varchar(255), AGE int)";
    public static String insert = "INSERT INTO TESTCONNECTDB (NAME, EMAIL, AGE) VALUES ('employee3', 'e3@gmail.com', 20)";
    public static String delete = "DELETE FROM TESTCONNECTDB WHERE NAME = 'employee1'";
    public static String queryAll = "SELECT * FROM TESTCONNECTDB";


//    exampleQueryManual(pool, queryAll)
//                .compose(nextItem -> exampleQueryManual(pool, insert)
//                        .compose(nextItem1 -> exampleQueryManual(pool, queryAll)
//                                .compose(nextItem2 -> exampleQueryManual(pool, delete)
//                                        .compose(nextItem3 -> exampleQueryManual(pool, queryAll)))));
}
